runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
- url: /images/(.*)
  static_files: images/\1
  upload: images/.*\.png
- url: /js/(.*)
  static_files: js/\1
  upload: js/.*\.js
- url: /(.*)
  static_files: \1
  upload: .*\.(html|css)
