application: stop-action
version: 0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /images/(.*)
  static_files: images/\1
  upload: images/.*\.png
- url: /(.*)
  static_files: \1
  upload: .*\.(js|html|css)
